name: geocoder_pro
description: A powerful Flutter package for forward and reverse geocoding, enabling easy conversion between addresses and geographic coordinates with support for multiple geocoding providers.
version: 1.0.3
homepage: https://github.com/rohitsoni9/geocoder_pro.git

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
