name: geocoder_pro
description: "A new Flutter package project."
version: 1.0.0
homepage: https://github.com/rohitsoni9/geocoder_pro.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
